
service: backend-java-api-user
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: us-west-2
  profile: serverless-sunshine
  apiGateway:
    shouldStartNameWithService: true

package:
  artifact: target/users-api-java-dev.jar

functions:
  user-api:
    handler: com.sunshine.Handler
    events:
      - http:
          path: /users/{email}/user
          method: get