
service: backend-java-api-user
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: us-west-2
  profile: serverless-sunshine

package:
  artifact: target/hello-dev.jar

functions:
  user-api:
    handler: com.serverless.Handler
    events:
      - http:
          path: user
          method: get