service: backend-java-api-user
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: us-west-2
  profile: serverless-sunshine
  apiGateway:
    shouldStartNameWithService: true
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}

package:
  artifact: target/users-api-java-dev.jar

functions:
  get-user-api:
    handler: com.sunshine.GetUserHandler
    events:
      - http:
          path: /users/{email}/user
          method: get
  save-user-api:
    handler: com.sunshine.SaveUserHandler
    events:
      - http:
          path: /users/{email}/user
          method: post