service: backend-java-api-user
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless-sunshine
  apiGateway:
    shouldStartNameWithService: true
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}

package:
  artifact: target/user-api-java-dev.jar

functions:
  get-user-api:
    handler: com.sunshine.GetUserHandler
    events:
      - http:
          path: /user/{email}
          method: get
          cors: true
  save-user-api:
    handler: com.sunshine.SaveUserHandler
    events:
      - http:
          path: /user/{email}/name/{userName}
          method: post
          cors: true
  delete-user-api:
    handler: com.sunshine.DeleteUserHandler
    events:
      - http:
          path: /user/{userID}
          method: delete
          cors: true